name: create pull request
on:
  pull_request:
   types: [opened, closed, reopened]
   branches:
      - main
jobs:
  Pull_request_test:
    runs-on: ubuntu-latest
    steps:
      - name: Print a Narendra name
        run: echo "Narendra"
      - name: Print a Vishwaja name
        run: echo "Vishwaja"
      - name: Print a Mounu name
        run: echo "Mounu"
      - name: Print a Suman name
        run: echo "Suman"
      - name: Print a Minni name
        run: echo "Minni"